
motivational_quotes = [
    "The secret to getting ahead is getting started.",
    "Dreams don’t work unless you do.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "The future depends on what you do today.",
    "The only way to do great work is to love what you do.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Discipline is choosing between what you want now and what you want most.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Small steps every day lead to big achievements over time.",
    "It always seems impossible until it’s done.",
    "Focus on the step in front of you, not the whole staircase.",
    "Every accomplishment starts with the decision to try.",
    "You are capable of amazing things.",
    "Progress, not perfection, is the key.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "The best way to predict the future is to create it.",
    "A little progress each day adds up to big results.",
    "Success is no accident. It is hard work and perseverance.",
    "Stay patient and trust the journey.",
    "Great things never come from comfort zones.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Don’t limit your challenges. Challenge your limits.",
    "If you believe in yourself, everything is possible.",
    "Work hard in silence, let success make the noise.",
    "Push yourself, because no one else is going to do it for you.",
    "The man on top of the mountain didn’t fall there.",
    "Winners are not people who never fail, but people who never quit.",
    "Believe in your infinite potential.",
    "One day or day one. You decide.",
    "Your energy introduces you before you even speak. Make it count.",
    "Hard work beats talent when talent doesn’t work hard.",
    "If you get tired, learn to rest, not quit.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t wait for opportunity. Create it.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "Your only limit is you.",
    "Fall seven times, stand up eight.",
    "What seems hard now will one day be your warm-up.",
    "Every second you spend wishing is a second you could use to build.",
    "If it doesn’t challenge you, it won’t change you.",
    "Nothing is impossible; the word itself says 'I’m possible!'",
    "Learn from yesterday, live for today, plan for tomorrow.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Your success tomorrow starts with your effort today.",
    "A journey of a thousand miles begins with a single step.",
    "Effort only fully releases its reward after a person refuses to quit.",
    "When you feel like quitting, think about why you started.",
    "Your growth tomorrow will thank your effort today."
]

# List of user guide sentences
user_guide_sentences = [
    "Traditional Pomodoro suggests four sessions per sitting.",
    "Each Pomodoro session lasts 25 minutes, followed by a 5-minute break.",
    "After four Pomodoro sessions, take a longer break of 15-30 minutes.",
    "Focus on one task during each session for maximum productivity.",
    "Avoid distractions during a session to make the most of the timer.",
    "Use the short breaks to stretch, hydrate, or relax your eyes.",
    "Plan your tasks ahead to ensure a seamless workflow.",
    "Start with smaller, easier tasks to build momentum.",
    "Reward yourself after completing a sitting for motivation.",
    "Customize your work-rest ratio if traditional Pomodoro feels restrictive.",
    "The Pomodoro technique encourages deep focus and minimal multitasking.",
    "Track your completed Pomodoro sessions to measure progress.",
    "Ensure your workspace is tidy to reduce distractions.",
    "Use the timer to break down big tasks into manageable chunks.",
    "Remember: Consistency is key to building habits with Pomodoro.",
    "In the sessions bar, 1 '🎯' counts as 4 '✔'."
]
